
#ifndef MY_PROJECTS_MOVEINFO_H
#define MY_PROJECTS_MOVEINFO_H

enum MoveInfo {
    ACCEPTED,
    GAME_FINISHED,
    ROUND_FINISHED,
    NOT_ALLOWED,
    EXCHANGE_STARTED
};

#endif //MY_PROJECTS_MOVEINFO_H
